### ISSUE TITLE
Please add version tags for repo

### ISSUE THREAD

**Issue by TomiS** [nielskrijger/BreadcrumbsBundle#1]
Hi and  thanks for a nice bundle.

Could you add some version tags for this repository. It would make it easier to use this bundle in projects where dependency management is done properly.

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by nielskrijger** [comment]
I've tagged current release with "v1.0.0". I presume that is sufficient for your needs. If not please let me know!
